services:
  database:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - main
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: dev

  core:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - main
    environment:
      - DATABASE_URL=mongodb://database:27017/dev
    depends_on:
      - database

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - main
    environment:
      - MONGODB_URI=mongodb://database:27017/dev
    depends_on:
      - core

networks:
  main:
      driver: bridge
      driver_opts:
        com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  mongo-data: