services:
  core:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - main

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - main
    depends_on:
      - core

networks:
  main:
      driver: bridge
      driver_opts:
        com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  mongo-data: